# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # corne peripherals (nice_nano_v2, 6col)
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_left_peripheral
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_left_peripheral
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right

  # fifi peripherals (nice_nano_v2, 5col)
  - board: nice_nano_v2
    shield: fifi_left
    artifact-name: fifi_left
  - board: nice_nano_v2
    shield: fifi_right
    artifact-name: fifi_right

  # dongle - corne (xiao ble, zmk studio enabled)
  - board: seeeduino_xiao_ble
    shield: corne_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_dongle
  # dongle - fifi (nice nano v2, with display)
  - board: nice_nano_v2
    shield: fifi_dongle dongle_display
    artifact-name: fifi_dongle

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset
