# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # board
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_left_peripheral
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_left_peripheral
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right_peripheral

  # dongle
  - board: seeeduino_xiao_ble
    shield: corne_dongle
    artifact-name: corne_dongle

  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset
