file_format: "1"
id: fifi
name: Fifi
type: shield
url: https://github.com/raychengy/fifi_split_keeb
requires: [pro_micro]
features:
  - keys
siblings:
  - corne_left
  - corne_left_peripheral
  - corne_right
  - corne_dongle
